### ISSUE TITLE
Any way to customize '/auth/:provider/callback' url?

### ISSUE THREAD

**Issue by sadfuzzy** [omniauth/omniauth#593]
Any way to customize '/auth/:provider/callback' url?
Is there any way? I want this to separate mobile applications and browser(any) response in Rails.
Something like '/auth/(:client)/:provider/callback' in my routes.
One - '/auth/:provider/callback'  for usual users(responds html).
Other - '/auth/mobile_app/:provider/callback' for ios/android(responds json, user auth_token).

**Comment by swaathi** [comment]
@sadfuzzy How did you go about this? If I put what @mbleigh suggested in an initializer it throws a  `undefined method 'provider'` error. Anyone else figure this out?

**Comment by pbrueske** [comment]
@sadfuzzy You can use the `OmniAuth::Builder` in an initializer (see https://github.com/omniauth/omniauth#getting-started) to set a custom callback path:

```ruby
# config/initializers/omniauth.rb
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :providername, :callback_path => "/auth/providername/mobile/callback"
end
```

**Comment by nantestdevoloper** [comment]
I want to call the api post call  url http://localhost:3000/api/v1/auth/identity/callback .please help me to understand how can I customize the post call and routes .so the in return will get success status ,because while calling post call like "http://localhost:3000/api/v1/auth/identity/callback " not able to generate the auth_hash and getting error in postman

NoMethodError at /api/v1/auth/identity/callback
===============================================

> undefined method `[]' for nil:NilClass

**Comment by twoneks** [comment]
What if I need to set a callback url that is external to my rails app domain?
The option `callback_path` only allow custom path in the scope of the application.

**Comment by jbranchaud** [comment]
> What if I need to set a callback url that is external to my rails app domain?
The option callback_path only allow custom path in the scope of the application.

@twoneks I'd recommend fielding the callback from your rails app and then redirecting to an external domain from there.
