### ISSUE TITLE
Error when trying to integrate with rails 5.0 api-only build

### ISSUE THREAD

**Issue by cbetta** [omniauth/omniauth#830]
Trying to integrate agains the Rails 5.0 `--api` flag (also know as `rails-api`) and getting this error:

`18:27:48 rails.1 | /Users/cbetta/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/omniauth-1.1.4/lib/omniauth/builder.rb:12:in`initialize': undefined method `<<' for nil:NilClass (NoMethodError)`

This happens on starting the app.

**Comment by md5** [comment]
I believe this is fixed in https://github.com/intridea/omniauth/pull/820. Try upgrading to OmniAuth 1.3.1.

**Comment by mmahalwy** [comment]
I get this: `OmniAuth::NoSessionError (You must provide a session to use OmniAuth.):`

**Comment by mbreedlove** [comment]
I'm on OmniAuth 1.3.1 and also get `OmniAuth::NoSessionError (You must provide a session to use OmniAuth.)`

**Comment by relevantmedia** [comment]
Same here: `OmniAuth::NoSessionError (You must provide a session to use OmniAuth.):`

**Comment by LuisCDias** [comment]
@relevantmedia @mbreedlove @mmahalwy did any of you get to solve this problem? I'm having it also and not sure what is the best way to proceed

**Comment by mmahalwy** [comment]
I haven't played around with Rails 5 since these problems.

**Comment by garethstokes** [comment]
was receiving the same error and this stackoverflow post helped me. worth checking out if working on a fix.

http://stackoverflow.com/questions/38424133/getting-error-omniauthnosessionerror-with-rails-5-api

**Comment by betoharres** [comment]
Same here

**Comment by mmahalwy** [comment]
So the only alternative I have found is using the `OAuth2` gem and doing everything manually. Let me know if it interests anyone and happy to share the code

**Comment by dlcmh** [comment]
@mmahalwy i'm interested, do share the code please - just for info, i'm having to implement a Rails 5 API-only solution for Twitter sign-in, but Twitter uses OAuth 1.0a, not OAuth2 - hopefully i'll be able to get some ideas from your implementation - thanks!

**Comment by oyeanuj** [comment]
@mmahalwy I am in the same boat as you, would love to see your solution!

**Comment by mmahalwy** [comment]
Google example:
```
class OauthController < ApplicationController
  TOKEN_ALGORITHM = 'HS256'

  def google
    google_token = OauthClient.auth_code.get_token(google_params, redirect_uri: Config::GOOGLE_API_CALLBACK)
    google_user  = google_token.get(Config::GOOGLE_API_USER_URL).parsed

    return head :unauthorized if google_user['hd'] != 'peek.com'

    render json: response_json(google_user), status: :ok
  rescue OAuth2::Error => e
    render json: { error: JSON.parse(e.response.body) }, status: :unauthorized
  end

private

  def google_params
    params.require(:code)
  end

  def response_json(google_user)
    {
      token: {
        access_token: generate_token(google_user),
        expires_at:   token_expiration
      },
      user:  google_user
    }
  end

  def generate_token(google_user)
    JWT.encode(token_payload(google_user), Config::SHARED_AUTH_SECRET, TOKEN_ALGORITHM)
  end

  def token_payload(google_user)
    now = Time.now.to_i
    {
      'iss' => 'SOME_ISS',
      'exp' => token_expiration,
      'nbf' => now - 60,     # available for use 1 minute before now
      'iat' => now,          # time issued
      'jti' => SecureRandom.uuid,
      'sub' => google_user['email']
    }.merge(google_user)
  end

  def token_expiration
    @token_expiration ||= Time.now.to_i + 86_400 # expires 1 day from now
  end
end
```

**Comment by alikhan-io** [comment]
Also suffering this problem. We tried cookie based storage but it errored out with CookieOverflows. So far Omniauth doesn't seem to respect active record store either.

**Comment by mltsy** [comment]
Can someone give an example of a use case where you are trying to use OmniAuth in an API-only application?  I'm having trouble imagining what that would look like (i.e. why you might need to allow authentication via multiple 3rd party services within an API)

In case it is helpful (which it might be, since it sounds like the lack of session middleware is the primary issue) I have implemented an API app where a few routes actually needed the session and cookie middleware (a couple non-API endpoints), but didn't want to muddy the rest of the API with that middleware, so I just [added a Rails Engine for those endpoints with the additional middleware](http://stackoverflow.com/questions/33982663/build-2-middleware-stacks-in-rails-app/41515577#41515577).  Perhaps you could use this approach to add session middleware to your authentication endpoints?

But that doesn't negate or resolve the issue/question of whether OmniAuth should be usable without the presence of a session... so I'm still curious what the use case is.

**Comment by alanwillms** [comment]
@mltsy My use case is an API for a Single Page Application where instead of cookies and sessions I use [Json Web Tokens](https://jwt.io/) for authentication. The token is sent as an `Authorization` header at every request.

**Comment by mltsy** [comment]
Okay, and... why does the API server need OmniAuth for that?  Does OmniAuth somehow handle the JWT for you?  Or are the JWTs from a 3rd party OAuth server?  What is the (theoretical) role of OmniAuth in this use case?

**Comment by alanwillms** [comment]
@mltsy my app users can sign in via Google or Facebook. Omniauth is a handy tool for that. Unfortunately, I cannot use it because it throws an `OmniAuth::NoSessionError`, since my app uses JWT and there is no sessions. It would be nice if Omniauth did not require sessions enabled.

Currently I am manually hitting those authentication APIs since I cannnot use this gem.

**Comment by alikhan-io** [comment]
Agreed with Alan. We essentially tried to use Angular2 with a Rails 5 API
backend leveraging OmniAuth + Devise along with a Devise add on for token
based authentication after the fact.

OmniAuth didn't allow for this without enabling sessions. In the end we
actually went with a 3rd Party Auth service (auth0) and used the knock gem.
We came to the conclusion in fairness to OmniAuth that it was built for
session based applications and hadn't been built considering SPAs with
separated front and back ends.

**Comment by mltsy** [comment]
Oooh, I see.  Yeah, I don't know if this is an issue with OmniAuth.  I would agree that OmniAuth is a gem built for session-based applications in general.  I mean if it could be used to some effect for something else, that would be great, but there are variables that need to be stored per-client somehow for some authentication methods (i.e. OAuth).  So if you're storing those things in an Angular App, then it makes sense to me that you would need to find a javascript-based solution, or proxy the authentication through another session-based application (Auth0).

However, an easy way to proxy them through a session-based app is, as I mentioned above, to just enable the session middleware for the OmniAuth routes in your API app ([using a rails engine](http://stackoverflow.com/questions/33982663/build-2-middleware-stacks-in-rails-app/41515577#41515577)), and bingo, you have a session-based authentication proxy using OmniAuth! :smile: (Without sacrificing performance on the rest of your API)

**Comment by halleyrv** [comment]
Hi I integrate devise_auth_token with omniauth, but when  for it to work I had to enable the midleware Session and Cokie. While it manages to authenticate and save in my users table the problem is that I do not have to recover the email and the token since as I said so that the validation can work I had to add midleware

The problem is that first omniauth does not respond json, what it does is show me a facebook login window and once it authenticates it saves my user if it does not exist and then redirects me to the next path

`http://localhost:3000/api/v1/auth/facebook/callback#_=_`

Here I leave the code If someone could help me integrate it with ember js in front end? How I can recovery token or data for user authenticated.


This is my code

first i add gem in gemfile

```
gem 'devise_token_auth'
gem 'omniauth-facebook'
```
then I create initializer in config/initializers/omniauth.rb and puts this code

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook,      ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET']
end 
```

In my route i put this code

```
namespace :api do
  	namespace :v1 do
  		mount_devise_token_auth_for 'User', at: 'auth'
  	end	
 end
```

In config/application.rb I add this midleware

```
config.middleware.insert_after ActiveRecord::Migration::CheckPending, ActionDispatch::Cookies
config.middleware.insert_after ActionDispatch::Cookies, ActionDispatch::Session::CookieStore
```

In my model User i puts this code

```
class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :omniauthable, :omniauth_providers => [:facebook]
          #,
          #:confirmable
  include DeviseTokenAuth::Concerns::User
end
```
In my application controller

```
class ApplicationController < ActionController::API
  before_action :authenticate_user!, unless: :devise_controller?
  include DeviseTokenAuth::Concerns::SetUserByToken

end
```

**Comment by mltsy** [comment]
@halleyrv I would open a new issue for this ticket if I were you, and since it doesn't seem like a bug with Omniauth, but just something you need help figuring out, I would also post it on StackOverflow.com with the tag `omniauth` rather than as an issue here.  Also, I'm not 100% clear on what it is you're asking, so when you do make a new post, be sure to identify the use case or workflow you're working on, the "desired outcome" and the "current outcome".  It seems like the use case is logging in a user successfully via Facebook's Oauth server using omniauth?  And it seems like what is happening is it is directing the browser to the URL you posted, but it's not clear what you're seeing at that URL, and what you would expect to happen instead :)

**Comment by halleyrv** [comment]
Hi @mltsy  Thanks for answering. I think that here I could put my doubt for advice. Regarding what the result is what I searched for in the middle of omniauth I respond in json format if I log in with facebook, currently what it does is redirect me to a url. I would like it to be able to return me in json format but could not get it

**Comment by alexventuraio** [comment]
As mentioned in this section [Integrating OmniAuth Into Your Rails API](https://github.com/omniauth/omniauth#integrating-omniauth-into-your-rails-api). Does that means now my app is using cookie session instead of a default `--api` rails app behavior? Or is it just for OmniAuth purposes and any security issue is actually present?
Because now I see that my Rails API creates a cookie in the browser. 🤔
