### ISSUE TITLE
Github security vulnerability alert CVE-2015-9284

### ISSUE THREAD

**Issue by bgwilson87** [omniauth/omniauth#960]
I received a security vulnerability alert from GitHub for omniauth, I am using 1.9.0

"The request phase of the OmniAuth Ruby gem is vulnerable to Cross-Site Request Forgery when used as part of the Ruby on Rails framework, allowing accounts to be connected without user intent, user interaction, or feedback to the user. This permits a secondary account to be able to sign into the web application as the primary account."

https://nvd.nist.gov/vuln/detail/CVE-2015-9284

![Screen Shot 2019-05-29 at 4 27 11 PM](https://user-images.githubusercontent.com/2334297/58589091-1c37bf00-822f-11e9-91c9-5879097c2066.png)

**Comment by bgwilson87** [comment]
Looks like some related discussion here https://github.com/omniauth/omniauth/pull/809

**Comment by gencer** [comment]
If this is considered as too risky and gets created in `CVE` why it isn't fixed since 2015? I hope this will be get fixed (or PR merged). Otherwise, alternatives...? Saying, What is our alternatives, by the way?

**Comment by cjheath** [comment]
Github is flagging "vulnerable dependency" in any repo that has omniauth in its _Gemfile.lock_. That's a *lot* of maintainers getting hassled over this, so it's important that someone expedites a fix.

**Comment by arye-dov-eidelman** [comment]
Is this still an issue if I only allow linking OmniAuth accounts that have the same email address as the logged in user?

**Comment by kodyclemens** [comment]
I believe it would still be vulnerable as long as the attacker knows the targeted user’s email address. The request is forged during the [request phase](https://github.com/omniauth/omniauth/wiki/Strategy-Contribution-Guide), so an attacker could pass the user’s email with a forged GitHub UID.

**Comment by tmilewski** [comment]
Let's please continue the conversation over at https://github.com/omniauth/omniauth/pull/809 so that we don't wind up with diverging discourses.

Thanks!

**Comment by aniketstiwari** [comment]
As I can see through the comments the PR(https://github.com/lunohodov/eventical/commit/b017fcf102c5796c4ad60a9ec9ff0a97a8bca08b) is not yet merge with the master so what we need to do in this case. I am also getting the same issue and below are my configuration

Rails - 5.2
Ruby - 2.5.3
omniauth (1.4.3)
omniauth-linkedin-oauth2 (1.0.0)
omniauth-oauth2 (1.5.0)
omniauth-google-oauth2 (0.6.1)

**Comment by mhamzajutt96** [comment]
This issue is not yet resolved, even I update all the gems and my Gemfile.lock also updated which is greater than 1.9
My Repository is: github.com/mhamzajutt96/sportscenter/network/alerts

**Comment by mathieujobin** [comment]
From the discussion above, it sounds like ...
- omniauth by itself isn't vulnerable
- rails by itself isn't vulnerable

some apps that do something very specific can be vulnerable.
like any apps that directly sends http query params to the database would be vulnerable to sql injection, would you blame MySQL for it?

it sounds like the CVE should be clarified and all that omniauth can do, is offer some documentation about it and a nice warning this using authentication gems isn't a guaranty of preventing security vulnerability within our applications

my two cents

**Comment by hakusaro** [comment]
@mathieujobin it is entirely unclear to me how anyone is supposed to contact NIST or GitHub to silence the alert on a site-wide scale or otherwise change the status of the alert to be more of an advisory warning against that behavior.

Plain and simple, the alert is too broad and does not adequately provide meaningful steps that can be taken to mitigate the problem. Instead, it scares everyone into a frenzy and causes people to disregard security alerts.

**Comment by aspiers** [comment]
The resolution is nicely documented here:

https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284

A few days ago I contacted CVE requesting they add that URL as a reference, and they have obliged.  So I think this issue can be closed now.

**Comment by ngoral** [comment]
In #809 it was said that for rails we should just use https://github.com/omniauth/omniauth

What's wrong with this solution over the one you suggest?

**Comment by aspiers** [comment]
The solution I have linked does use omniauth/omniauth.  The solution is to use it in the right way.

**Comment by ngoral** [comment]
I'm sorry, I definitely meant `omniauth-rails`, not simply `omniauth`. However, it appears I missed that the thread in #809 is far longer than I noticed (GitHub had just cut the rest of the messages). I've read till the end now and see `omniauth-rails` hasn't been ready yet.

**Comment by CHTJonas** [comment]
It seems like `omniauth-rails` is a bit of a nascent repo. I think the idea was to incorporate Rails-specific CSRF stuff in there but that hasn't happened yet (and there'd be a lot of inertia to get everyone to change their `Gemfile`s.

**Comment by pebneter** [comment]
I think you should be looking here (kind of the final solution): https://github.com/cookpad/omniauth-rails_csrf_protection

**Comment by aspiers** [comment]
> I think you should be looking here (kind of the final solution): cookpad/omniauth-rails_csrf_protection

Installing https://github.com/cookpad/omniauth-rails_csrf_protection is great for introducing protection to your app, but it is not sufficient by itself; as its own README says:

> You will then need to verify that all links in your application that would initiate OAuth request phase are being converted to a HTTP POST form that contains authenticity_token value.

The [Resolving-CVE-2015-9284 wiki page I previously posted](https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284) already suggests installing the above gem as the first of several steps, plus it goes into much greater detail explaining why this is all necessary and how to perform the other steps too.  Therefore the wiki page is the best link to recommend to people looking for solutions, not the gem which is only one part of the solution.

**Comment by zhengxiangyue** [comment]
> The resolution is nicely documented here:
> 
> https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284
> 
> A few days ago I contacted CVE requesting they add that URL as a reference, and they have obliged. So I think this issue can be closed now.

This doesn't work for me because my provider only supports `GET` method to redirect to their login page.

**Comment by aspiers** [comment]
[**@zhengxiangyue**](https://github.com/zhengxiangyue) commented on [March 16, 2020 9:52 PM](https://github.com/omniauth/omniauth/issues/960#issuecomment-599774459 "2020-03-16T21:52:32Z - Replied by Github Reply Comments"):
> > The resolution is nicely documented here:
> > 
> > [omniauth/omniauth/wiki/Resolving-CVE-2015-9284](https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284)
> > 
>
> This doesn't work for me because my provider only supports `GET` method to redirect to their login page.

That sounds like an issue with your provider, not with omniauth itself.

**Comment by Papipo** [comment]
Is omniauth abandoned?

**Comment by BobbyMcWho** [comment]
@Papipo there's a lot of work to be done and not enough folks to do the work unfortunately. I've only recently become a co-maintainer of the project and I do not personally have enough time to weed through stale issues and PRs, and also not enough time to code the solutions. 

That being said, if someone makes a new PR or issue, I'll do my best to respond to it in a timely manner. I know this CVE is longstanding but because it would require breaking changes to resolve, it's not something that I feel comfortable rushing out.

**Comment by schlenks** [comment]
Given that this has been a long standing issue, and has it's own dedicated wiki page, has there been any consideration to releasing a v2.0.0 that has the breaking change of only supporting `POST` requests? That'd allow an upgrade path that doesn't involve instructing bundler-audit to ignore a CVE.

**Comment by josh-m-sharpe** [comment]
@BobbyMcWho There's been more than a few PRs, new gems and ideas.  That part has been done.  As maintainer, it's your responsibility to lead and direct the masses.  I don't see that being done.

The wiki page describing the CVE issue and its mitigation is a good step.  How about you create a page with a proposed solution so that someone can pick up the reigns and build/test the PR for your review?

**Comment by BobbyMcWho** [comment]
@josh-m-sharpe there has been nothing new submitted that I haven't reviewed and/or merged since I've started to help maintain this. I'll reiterate again that I don't personally have the time to make this fix. 

I started helping out to maintain this library because new PRs and issues were being ignored, and I figured _some_ maintenance was better than none. I've been pretty good at responding, reviewing, and merging new items coming in a timely manner. 

It is not my responsibility to "lead and direct the masses". I don't have the community clout nor the reach to try and do that. I'm happy with my scope of involvement in this project, and again, if you submit a PR that fixes this in a way that makes sense for the library, I'll work to get it reviewed, merged, and released under an appropriate version number for the change. 

Have a great weekend 🙂

**Comment by josh-m-sharpe** [comment]
I apologize if my first message wasn't clear.  I'm absolutely not suggesting that you (or any other maintainer) is responsible to build the fix for this.  But, as the maintainers, I would think that you know better than others what is in the best interest of the library.

Set that stage and and the PR will follow :)

**Comment by Papipo** [comment]
> I apologize if my first message wasn't clear.

I am afraid that your first message was pretty clear.

**Comment by BobbyMcWho** [comment]
I'm open for comments/review on this PR: https://github.com/omniauth/omniauth/pull/1010

**Comment by BobbyMcWho** [comment]
I've opened a discussion on a v2.0.0 release candidate: https://github.com/omniauth/omniauth/discussions/1017

**Comment by BobbyMcWho** [comment]
The vulnerable by default configuration has been removed in the [v2.0.0 release](https://github.com/omniauth/omniauth/releases/tag/v2.0.0)

**Comment by jeremiemv** [comment]
Thank you for all your work @BobbyMcWho

**Comment by robotarmy** [comment]
@bobbymcwho - is this the patch that introduced throwing query params on-to the redirect_uri ?
