### ISSUE TITLE
1 omniauth vulnerability found in Gemfile.lock

### ISSUE THREAD

**Issue by exchangedeb** [omniauth/omniauth#972]
Please complete all sections.

### Configuration

- Provider Gem: `omniauth-*`
- Ruby Version: `5.2.3`
- Framework: `Rails`
- Platform: `Ubuntu 16.04`

### Expected Behavior

Tell us what should happen.

After i deploy my Rails code at GitHUb it shows 1 omniauth vulnerability found in Gemfile.lock
Remediation
No patched version is available.
### Actual Behavior
https://github.com/FreelancerMasum/finaldev/network/alert/Gemfile.lock/omniauth/open
Tell us what happens instead.
![Screenshot from 2019-10-01 13-08-29](https://user-images.githubusercontent.com/55578382/65941480-f163ae80-e44c-11e9-9a40-3f778372a59f.png)

### Steps to Reproduce

Please list all steps to reproduce the issue.

**Comment by alexventuraio** [comment]
Any proposal to fix it up?

**Comment by rrjohnson85** [comment]
Isn't this covered in the Wiki, https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284?

**Comment by alexventuraio** [comment]
@rrjohnson85 yeah I see that we need to use a new gem to fix that issue.
One more question, if I'm using [omniauth-github](https://github.com/omniauth/omniauth-github) is there a way I can fix the same issue but in that gem?
Since the GitHub strategy gem is using `omniauth` gem I think that's way I get the same vulnerability issue :( .

Thanks in advance!

**Comment by BobbyMcWho** [comment]
Duplicate of https://github.com/omniauth/omniauth/issues/960
